version: "3.3"

services:
  db:
    image: tgrundtvig/codechecksql
    environment:
      - MYSQL_USER=Edutor
      - MYSQL_PASSWORD=qwerty123
      - MYSQL_ROOT_PASSWORD=qwerty123
      - MYSQL_DATABASE=CBA_Code_Check
    ports:
      - 3306:3306
      
  web:
    image: tgrundtvig/codecheckwar
    ports: 
      - 80:8080
    links: 
      - db:database